/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LUCKY' at '5/19/17 6:52 AM' with Gradle 2.14.1
 *
 * @author LUCKY, @date 5/19/17 6:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
